name: Release Userscript

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '20'
        
    - name: Extract version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        
    - name: Update version in header
      run: |
        # Update userscript version in source
        sed -i "s/@version      [0-9.-]*[a-z]*/@version      ${{ steps.get_version.outputs.version }}/" src/userscript-header.txt
        echo "Updated userscript version to ${{ steps.get_version.outputs.version }}"
        grep "@version" src/userscript-header.txt
        
    - name: Build userscript
      run: |
        node build.js
        echo "Built userscript successfully"
        ls -la dist/
        
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create v${{ steps.get_version.outputs.version }} \
          --title "FicTrail v${{ steps.get_version.outputs.version }}" \
          --notes "## FicTrail v${{ steps.get_version.outputs.version }}

        ### Installation
        1. Install [Tampermonkey](https://www.tampermonkey.net/) browser extension
        2. Click on the userscript file below to install it
        3. Visit any [AO3 page](https://archiveofourown.org/) and click the FicTrail button to start using it

        ### Changes
        See the commit history for detailed changes in this release." \
          ./dist/fictrail.user.js
